export const equipos = [{}];

export const partidos = [
  {
    id: 49,
    venue: "Khalifa International Stadium",
    location: "Ar-Rayyan",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "NED",
    away_team_country: "USA",
    datetime: "2022-12-03T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "NED",
      name: "Netherlands",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "USA",
      name: "United States",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:27Z",
    last_changed_at: "2022-12-02T22:37:27Z",
  },
  {
    id: 50,
    venue: "Ahmad Bin Ali Stadium",
    location: "Ar-Rayyan",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "ARG",
    away_team_country: "AUS",
    datetime: "2022-12-03T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "ARG",
      name: "Argentina",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "AUS",
      name: "Australia",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:27Z",
    last_changed_at: "2022-12-02T22:37:27Z",
  },
  {
    id: 51,
    venue: "Al Thumama Stadium",
    location: "Doha",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "FRA",
    away_team_country: "POL",
    datetime: "2022-12-04T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "FRA",
      name: "France",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "POL",
      name: "Poland",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:26Z",
    last_changed_at: "2022-12-02T22:37:26Z",
  },
  {
    id: 52,
    venue: "Al Bayt Stadium",
    location: "Al Khor",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "ENG",
    away_team_country: "SEN",
    datetime: "2022-12-04T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "ENG",
      name: "England",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "SEN",
      name: "Senegal",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:26Z",
    last_changed_at: "2022-12-02T22:37:26Z",
  },
  {
    id: 53,
    venue: "Al Janoub Stadium",
    location: "Al Wakrah",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "JPN",
    away_team_country: "CRO",
    datetime: "2022-12-05T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "JPN",
      name: "Japan",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "CRO",
      name: "Croatia",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:26Z",
    last_changed_at: "2022-12-02T22:37:26Z",
  },
  {
    id: 54,
    venue: "Stadium 974",
    location: "Doha",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "BRA",
    away_team_country: "KOR",
    datetime: "2022-12-05T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "BRA",
      name: "Brazil",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "KOR",
      name: "Korea Republic",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:27Z",
    last_changed_at: "2022-12-02T22:37:27Z",
  },
  {
    id: 55,
    venue: "Education City Stadium",
    location: "Doha",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "MAR",
    away_team_country: "ESP",
    datetime: "2022-12-06T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "MAR",
      name: "Morocco",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "ESP",
      name: "Spain",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:26Z",
    last_changed_at: "2022-12-02T22:37:26Z",
  },
  {
    id: 56,
    venue: "Lusail Stadium",
    location: "Al Daayen",
    status: "future_scheduled",
    attendance: null,
    stage_name: "Round of 16",
    home_team_country: "POR",
    away_team_country: "SUI",
    datetime: "2022-12-06T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      country: "POR",
      name: "Portugal",
      goals: null,
      penalties: null,
    },
    away_team: {
      country: "SUI",
      name: "Switzerland",
      goals: null,
      penalties: null,
    },
    last_checked_at: "2022-12-02T22:37:27Z",
    last_changed_at: "2022-12-02T22:37:27Z",
  },
  {
    id: 57,
    venue: "Education City Stadium",
    location: "Doha",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Quarter-final",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-09T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "W53",
    },
    away_team: {
      name: "To Be Determined",
      country: "W54",
    },
    last_checked_at: "2022-12-02T22:37:27Z",
    last_changed_at: "2022-11-20T21:29:29Z",
  },
  {
    id: 58,
    venue: "Lusail Stadium",
    location: "Al Daayen",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Quarter-final",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-09T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "W49",
    },
    away_team: {
      name: "To Be Determined",
      country: "W50",
    },
    last_checked_at: "2022-12-02T22:37:27Z",
    last_changed_at: "2022-11-20T21:29:16Z",
  },
  {
    id: 59,
    venue: "Al Thumama Stadium",
    location: "Doha",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Quarter-final",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-10T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "W55",
    },
    away_team: {
      name: "To Be Determined",
      country: "W56",
    },
    last_checked_at: "2022-12-02T22:37:26Z",
    last_changed_at: "2022-11-20T21:29:20Z",
  },
  {
    id: 60,
    venue: "Al Bayt Stadium",
    location: "Al Khor",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Quarter-final",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-10T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "W51",
    },
    away_team: {
      name: "To Be Determined",
      country: "W52",
    },
    last_checked_at: "2022-12-02T22:37:26Z",
    last_changed_at: "2022-11-20T21:29:24Z",
  },
  {
    id: 61,
    venue: "Lusail Stadium",
    location: "Al Daayen",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Semi-final",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-13T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "W57",
    },
    away_team: {
      name: "To Be Determined",
      country: "W58",
    },
    last_checked_at: "2022-12-02T22:37:26Z",
    last_changed_at: "2022-11-20T21:29:25Z",
  },
  {
    id: 62,
    venue: "Al Bayt Stadium",
    location: "Al Khor",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Semi-final",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-14T19:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "W59",
    },
    away_team: {
      name: "To Be Determined",
      country: "W60",
    },
    last_checked_at: "2022-12-02T22:37:27Z",
    last_changed_at: "2022-11-20T21:29:26Z",
  },
  {
    id: 63,
    venue: "Khalifa International Stadium",
    location: "Ar-Rayyan",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Play-off for third place",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-17T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "RU61",
    },
    away_team: {
      name: "To Be Determined",
      country: "RU62",
    },
    last_checked_at: "2022-12-02T22:37:28Z",
    last_changed_at: "2022-11-20T21:29:31Z",
  },
  {
    id: 64,
    venue: "Lusail Stadium",
    location: "Al Daayen",
    status: "future_unscheduled",
    attendance: null,
    stage_name: "Final",
    home_team_country: null,
    away_team_country: null,
    datetime: "2022-12-18T15:00:00Z",
    winner: null,
    winner_code: null,
    home_team: {
      name: "To Be Determined",
      country: "W61",
    },
    away_team: {
      name: "To Be Determined",
      country: "W62",
    },
    last_checked_at: "2022-12-02T22:37:28Z",
    last_changed_at: "2022-11-20T21:29:17Z",
  },
];
